### ISSUE TITLE
gcc10+ build issues

### ISSUE THREAD

**Issue by nicholi** [medooze/libdatachannels#1]
Missing std header usage (in context of building with medooze-media-server).

```
In file included from ../media-server/include/media.h:10,
                 from ../media-server/include/rtp/RTPPacket.h:17,
                 from ../media-server/include/rtp/RTPIncomingMediaStream.h:18,
                 from ../media-server/include/ActiveSpeakerMultiplexer.h:4,
                 from ../media-server/src/ActiveSpeakerMultiplexer.cpp:1:
../media-server/ext/libdatachannels/src/internal/BufferReader.h: In member function ‘uint64_t BufferReader::DecodeLev128()’:
../media-server/ext/libdatachannels/src/internal/BufferReader.h:137:29: error: ‘numeric_limits’ is not a member of ‘std’
  137 |                 return std::numeric_limits<uint64_t>::max();
      |                             ^~~~~~~~~~~~~~
../media-server/ext/libdatachannels/src/internal/BufferReader.h:137:52: error: expected primary-expression before ‘>’ token
  137 |                 return std::numeric_limits<uint64_t>::max();
      |                                                    ^
../media-server/ext/libdatachannels/src/internal/BufferReader.h:137:55: error: ‘::max’ has not been declared; did you mean ‘std::max’?
  137 |                 return std::numeric_limits<uint64_t>::max();
      |                                                       ^~~
      |                                                       std::max
```

It seems past versions of gcc were possibly adding this header by default. Only noticed when attempting to build on Ubuntu 21.10 (which is now on gcc-11).

Simple temp workaround, get gcc-9 or earlier and `export CC=gcc-9 CXX=g++-9`
